# Generated by Django 5.0.1 on 2024-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
